"""Default skill definitions and current dataset-to-skill coverage."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .skills import Skill, SkillLibrary


def _skill(name: str, category: str, *,
           inputs=(), outputs=(), pre=(), post=(), clears=(),
           sensors=(), control="cartesian_position", objects=("*",),
           robots=("*",), evidence=(), description="") -> Skill:
    return Skill(
        name=name,
        category=category,
        input_states=tuple(inputs),
        output_states=tuple(outputs),
        preconditions=tuple(frozenset(option) for option in (pre or ((),))),
        postconditions=frozenset(post),
        clears=frozenset(clears),
        sensors=tuple(sensors),
        control_mode=control,
        object_kinds=tuple(objects),
        robot_types=tuple(robots),
        evidence_sources=tuple(evidence),
        description=description,
    )


def default_skill_library() -> SkillLibrary:
    """Return the first reusable skill vocabulary used by the mining layer."""
    return SkillLibrary([
        _skill("approach", "motion", inputs=("visible",), outputs=("aligned",),
               pre=(("visible",),), post=("aligned",), clears=("far",),
               sensors=("camera.rgb", "robot.end_effector_pose"),
               evidence=("LeRobot", "ROS bag", "UMI", "VR"),
               description="接近目标并进入可操作距离"),
        _skill("align", "motion", inputs=("visible",), outputs=("aligned",),
               pre=(("visible",),), post=("aligned",), clears=("misaligned",),
               sensors=("camera.rgb", "robot.end_effector_pose"),
               evidence=("LeRobot", "ROS bag", "UMI", "VR"),
               description="把末端、目标和操作方向对齐"),
        _skill("grasp", "contact", inputs=("aligned", "hand_open"),
               outputs=("grasped", "hand_closed"),
               pre=(("aligned", "hand_open", "object_free"),
                    ("aligned", "hand_open")),
               post=("grasped", "hand_closed"), clears=("hand_open", "object_free"),
               sensors=("camera.rgb", "umi.gripper_width", "sensor.force_torque",
                        "sensor.tactile"),
               control="position_gripper",
               evidence=("LeRobot", "ROS bag", "Fourier HDF5"),
               description="建立并保持有效夹持"),
        _skill("lift", "motion", inputs=("grasped",), outputs=("lifted",),
               pre=(("grasped",),), post=("lifted",), clears=("supported_surface",),
               sensors=("robot.end_effector_pose", "robot.joint_position"),
               evidence=("LeRobot", "ROS bag", "UMI"),
               description="在保持夹持的条件下离开支撑面"),
        _skill("transport", "motion", inputs=("lifted",), outputs=("transported",),
               pre=(("lifted",), ("grasped",)),
               post=("transported",), sensors=("robot.end_effector_pose",),
               evidence=("LeRobot", "ROS bag", "UMI"),
               description="携带目标移动到新的空间位置"),
        _skill("place", "contact", inputs=("lifted", "target_reachable"),
               outputs=("placed", "supported_surface"),
               pre=(("lifted", "target_reachable"),
                    ("transported", "target_reachable"),
                    ("grasped", "target_reachable")),
               post=("placed", "supported_surface"),
               clears=("lifted", "transported"),
               sensors=("camera.rgb", "robot.end_effector_pose",
                        "sensor.force_torque"),
               control="cartesian_position",
               evidence=("LeRobot", "ROS bag", "Fourier HDF5"),
               description="把目标放到支撑或目标位置"),
        _skill("release", "contact", inputs=("placed", "hand_closed"),
               outputs=("released", "hand_open"),
               pre=(("placed", "hand_closed"), ("grasped", "hand_closed")),
               post=("released", "hand_open"), clears=("grasped", "hand_closed"),
               sensors=("umi.gripper_width", "sensor.force_torque"),
               control="position_gripper",
               evidence=("LeRobot", "ROS bag", "Fourier HDF5"),
               description="确认目标有支撑后释放夹持"),
        _skill("handover", "coordination", inputs=("grasped", "receiver_ready"),
               outputs=("transferred", "receiver_grasped"),
               pre=(("grasped", "receiver_ready"),),
               post=("transferred", "receiver_grasped"),
               clears=("grasped",),
               sensors=("camera.rgb", "sensor.force_torque", "sensor.tactile"),
               control="dual_arm",
               evidence=("Galaxea", "RoboTwin2", "RoboMind"),
               description="两个末端之间完成安全交接"),
        _skill("open", "articulation", inputs=("closed",), outputs=("open",),
               pre=(("closed",),), post=("open",), clears=("closed",),
               sensors=("camera.rgb", "sensor.force_torque"),
               control="force_position",
               objects=("articulated", "rigid"),
               evidence=("RoboTwin2", "RoboMind"),
               description="打开容器、柜门或其他铰接部件"),
        _skill("close", "articulation", inputs=("open",), outputs=("closed",),
               pre=(("open",),), post=("closed",), clears=("open",),
               sensors=("camera.rgb", "sensor.force_torque"),
               control="force_position",
               objects=("articulated", "rigid"),
               evidence=("RoboTwin2", "RoboMind"),
               description="关闭容器、柜门或其他铰接部件"),
        _skill("wipe", "contact", inputs=("grasped",), outputs=("surface_clean",),
               pre=(("grasped",), ("tool_grasped",)),
               post=("surface_clean",),
               sensors=("camera.rgb", "sensor.force_torque", "sensor.tactile"),
               control="force_position",
               objects=("rigid", "deformable_surface", "cloth", "soft_tool"),
               evidence=("AgiBotWorld", "Galaxea", "RoboMind"),
               description="沿表面维持接触并完成擦拭"),
        _skill("flatten", "deformable", inputs=("visible",), outputs=("flattened",),
               pre=(("visible",),), post=("flattened",), clears=("folded",),
               sensors=("camera.rgb", "robot.end_effector_pose"),
               control="dual_arm",
               objects=("deformable_surface", "cloth", "bag"),
               evidence=("AgiBotWorld", "Galaxea", "逐际动力", "乐聚"),
               description="展开并摊平柔性表面"),
        _skill("fold", "deformable", inputs=("flattened",), outputs=("folded",),
               pre=(("flattened",), ("visible",)),
               post=("folded",), clears=("flattened",),
               sensors=("camera.rgb", "robot.end_effector_pose", "sensor.tactile"),
               control="dual_arm",
               objects=("deformable_surface", "cloth", "bag"),
               evidence=("AgiBotWorld", "Galaxea", "逐际动力", "乐聚"),
               description="沿折叠线改变柔性物体形状"),
        _skill("smooth", "deformable", inputs=("visible",), outputs=("smoothed",),
               pre=(("visible",),), post=("smoothed",),
               sensors=("camera.rgb", "robot.end_effector_pose"),
               control="force_position",
               objects=("deformable_surface", "cloth", "bag"),
               evidence=("AgiBotWorld", "Galaxea", "逐际动力"),
               description="抚平褶皱或局部不平整"),
        _skill("hang", "deformable", inputs=("grasped", "hook_visible"),
               outputs=("hung",), pre=(("grasped", "hook_visible"),),
               post=("hung",), clears=("lifted",),
               sensors=("camera.rgb", "robot.end_effector_pose",
                        "sensor.force_torque"),
               control="cartesian_position",
               objects=("cloth", "bag", "rope", "rigid"),
               evidence=("AgiBotWorld", "Galaxea", "逐际动力"),
               description="把物体挂到挂点或支撑物上"),
        _skill("insert", "contact", inputs=("grasped", "target_open"),
               outputs=("inserted",), pre=(("grasped", "target_open"),),
               post=("inserted",),
               sensors=("camera.rgb", "robot.end_effector_pose",
                        "sensor.force_torque"),
               control="force_position",
               objects=("rigid", "articulated", "soft_tool"),
               evidence=("RoboTwin2", "RoboMind", "OpenLET"),
               description="将物体或工具插入目标开口"),
        _skill("rotate", "contact", inputs=("grasped", "aligned"),
               outputs=("rotated",), pre=(("grasped", "aligned"),),
               post=("rotated",), sensors=("camera.rgb", "sensor.force_torque"),
               control="force_position",
               objects=("rigid", "articulated", "soft_tool"),
               evidence=("RoboTwin2", "RoboMind", "OpenLET"),
               description="保持接触并改变目标朝向"),
        _skill("push", "contact", inputs=("aligned",), outputs=("pushed",),
               pre=(("aligned",),), post=("pushed",),
               sensors=("camera.rgb", "robot.end_effector_pose",
                        "sensor.force_torque"),
               control="force_position",
               objects=("rigid", "deformable_surface", "cloth", "bag"),
               evidence=("RoboTwin2", "RoboMind", "OpenLET"),
               description="沿受控方向推动目标"),
        _skill("pull", "contact", inputs=("aligned",), outputs=("pulled",),
               pre=(("aligned",),), post=("pulled",),
               sensors=("camera.rgb", "robot.end_effector_pose",
                        "sensor.force_torque"),
               control="force_position",
               objects=("rigid", "deformable_surface", "cloth", "bag", "rope"),
               evidence=("RoboTwin2", "RoboMind", "逐际动力"),
               description="沿受控方向拉动目标"),
        _skill("sort", "manipulation", inputs=("grasped", "target_reachable"),
               outputs=("sorted",),
               pre=(("grasped", "target_reachable"), ("placed",)),
               post=("sorted",),
               sensors=("camera.rgb", "robot.end_effector_pose"),
               evidence=("乐聚", "RoboMind", "OpenLET"),
               description="依据目标类别或位置完成分类"),
        _skill("pour", "contact", inputs=("grasped", "receptacle_open"),
               outputs=("poured",), pre=(("grasped", "receptacle_open"),),
               post=("poured",), sensors=("camera.rgb", "robot.end_effector_pose"),
               control="cartesian_position",
               objects=("rigid", "soft_tool"),
               evidence=("RoboMind", "OpenLET"),
               description="改变容器姿态使内容物流出"),
        _skill("press", "contact", inputs=("aligned",), outputs=("pressed",),
               pre=(("aligned",),), post=("pressed",),
               sensors=("camera.rgb", "sensor.force_torque", "sensor.tactile"),
               control="force_position",
               objects=("rigid", "articulated", "soft_tool"),
               evidence=("OpenLET", "RoboTwin2", "RoboMind"),
               description="向目标施加受控按压力"),
    ])


@dataclass(frozen=True)
class DatasetSkillSource:
    dataset_id: str
    display_name: str
    format: str
    strengths: tuple[str, ...] = ()
    example_tasks: tuple[str, ...] = ()
    execution_level: str = "robot_action"
    notes: tuple[str, ...] = ()
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "dataset_id": self.dataset_id,
            "display_name": self.display_name,
            "format": self.format,
            "strengths": list(self.strengths),
            "example_tasks": list(self.example_tasks),
            "execution_level": self.execution_level,
            "notes": list(self.notes),
            "metadata": dict(self.metadata),
        }


def dataset_skill_sources() -> tuple[DatasetSkillSource, ...]:
    """Current local portal inventory, expressed as reusable-skill coverage."""
    return (
        DatasetSkillSource(
            "leju", "乐聚", "LeRobot v2.1",
            strengths=("grasp", "place", "transport", "sort", "fold", "wipe"),
            example_tasks=("桌面零件抓放", "输送办公物品", "快递包裹分拣",
                           "叠毛巾", "抹布擦桌面"),
            metadata={"approx_hours": 1300, "task_rows": 2475},
        ),
        DatasetSkillSource(
            "zhujidongli", "逐际动力", "LeRobot v3.0",
            strengths=("fold", "flatten", "grasp", "place", "pull", "open"),
            example_tasks=("叠T恤", "固定/随机位置叠衣服", "抓放香蕉",
                           "抓柠檬", "夹水瓶", "拉抽屉", "开箱子"),
            metadata={"approx_hours": 200, "task_rows": 196},
        ),
        DatasetSkillSource(
            "agibotworld_beta", "AgiBotWorld-Beta", "LeRobot v3.0",
            strengths=("flatten", "fold", "hang", "wipe", "sort", "handover"),
            example_tasks=("摊平短裤", "折叠短袖", "挂衣服",
                           "从洗衣机取衣服", "软编织袋打包", "抹布擦污渍"),
            metadata={"task_subsets": 205, "episodes": 162391},
        ),
        DatasetSkillSource(
            "galaxea", "Galaxea", "LeRobot v3.0",
            strengths=("handover", "flatten", "fold", "wipe", "transport",
                       "sort"),
            example_tasks=("双臂整理衣物", "挂毛巾", "铺平桌布",
                           "清洁镜子/水槽/案板", "搬水果、瓶子、碗"),
            metadata={"task_subsets": 227, "episodes": 22626},
        ),
        DatasetSkillSource(
            "robotwin2", "RoboTwin2", "LeRobot v3.0 simulation",
            strengths=("handover", "grasp", "place", "open", "close",
                       "insert", "rotate"),
            example_tasks=("双臂交接", "叠积木", "开柜子", "开微波炉",
                           "拿取放置", "旋转和扫描"),
            execution_level="simulation_action",
            notes=("仿真证据可用于组合和变体覆盖，不等于真机执行证明",),
            metadata={"task_subsets": 458, "episodes": 125500,
                      "robot_families": 5},
        ),
        DatasetSkillSource(
            "robomind", "RoboMind", "LeRobot v3.0",
            strengths=("grasp", "place", "insert", "wipe", "open", "close",
                       "sort", "handover"),
            example_tasks=("拿盘子放入架子", "拿刷子清洁杯子",
                           "打开盖子放入物体再关闭", "多物体收纳"),
            metadata={"task_subsets": 363, "episodes": 61043},
        ),
        DatasetSkillSource(
            "openlet", "OpenLET", "ROS bag",
            strengths=("grasp", "place", "press", "push", "pull", "rotate",
                       "insert"),
            example_tasks=("零件分拣", "箱体对齐", "瓶子递送",
                           "牙膏盒收纳", "软物触碰"),
            notes=("可见部分控制器命令、力/触觉通道，但不等于完整电机内部状态",),
            metadata={"sample_groups": ("base", "dex", "body")},
        ),
        DatasetSkillSource(
            "umi_ego_vr", "UMI / Ego / VR", "Zarr / MP4 / VR",
            strengths=("approach", "align", "grasp", "flatten", "fold",
                       "wipe"),
            example_tasks=("第一视角手部操作", "柔性物体观察", "场景阶段识别"),
            execution_level="visual_or_end_effector",
            notes=("可用于视觉和阶段识别；没有机器人本体 action 时不能直接执行"),
        ),
        DatasetSkillSource(
            "fourier", "傅利叶", "专有 HDF5",
            strengths=("grasp", "place", "transport", "handover"),
            example_tasks=("双臂物体操作", "基座/末端力信息采集"),
            notes=("保留双腕力和观测基座位姿；字段语义仍需按机型校验",),
        ),
    )


def skill_catalog() -> dict:
    library = default_skill_library()
    return {
        "schema": "organoid-kernel.skill-catalog.v1",
        "skills": [library.get(name).to_dict() for name in library.names()],
        "dataset_sources": [source.to_dict() for source in dataset_skill_sources()],
    }
